clock: clock
reset: reset
cpu_req_valid: io_cpu_req_valid
cpu_req_ready: io_cpu_req_ready
cpu_req_addr: io_cpu_req_bits_addr
cpu_req_write: io_cpu_req_bits_write
cpu_req_wdata: io_cpu_req_bits_wdata
cpu_req_wmask: io_cpu_req_bits_wmask
cpu_resp_valid: io_cpu_resp_valid
cpu_resp_ready: io_cpu_resp_ready
cpu_resp_rdata: io_cpu_resp_bits_data

